model_parameters:
  dropout_probab: 0.35
  kernel_conv_1: 2
  kernel_conv_2: 3
  kernel_conv_3: 5
  kernel_pool: 2
  num_classes: 2
  out_conv_1: 6
  out_conv_2: 16
  out_conv_3: 40
  out_fc1: 400
  out_fc2: 200
  out_fc3: 84
  padding_conv_1: 2
  padding_conv_2: 2
  padding_conv_3: 2
  padding_pool: 0
  stride_conv_1: 1
  stride_conv_2: 1
  stride_conv_3: 1
  stride_pool: 2
preprocessing:
  address_for_mel_spectrograms: /Users/cookie/dev/m_loudener/audio_files/_train_test_dataset/mels_
  after_trim: pad
  duration_sec: 1.4
  fft_hop: 512
  fft_size: 2048
  filter_dc: true
  fmax: 8000
  librosa_trim_db: 15
  mel_power: 1
  mel_size: 512
  number_of_files_per_class_train: 10
  number_of_files_test: 2
  number_of_files_train: 10
  number_of_shifted_spectrograms: 1
  sample_rate: 16000
  stft_center: false
  time_size: 40
  to_save_pickles: null
  train_test_files_destination_folder: /Users/cookie/dev/m_loudener/audio_files/_train_test_dataset/
train_loop:
  classes:
    c_1: Full_Mix
    c_2: Solo
  gamma: 0.5
  learning_rate: 2.0e-06
  model_results_address: /model_results/m_loudener/
  num_epochs: 280
  step_size: 75
  type_of_training: new
  validation_set: /Users/cookie/dev/m_loudener/audio_files/_train_test_dataset/Validation_Set/
  x_test_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_2_classes_1.4_seconds_20240327-202050/test_x_m_loudener_2_classes_1.4_seconds_20240327-202050
  x_train_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_2_classes_1.4_seconds_20240327-202050/train_x_m_loudener_2_classes_1.4_seconds_20240327-202050
  y_test_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_2_classes_1.4_seconds_20240327-202050/test_y_m_loudener_2_classes_1.4_seconds_20240327-202050
  y_train_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_2_classes_1.4_seconds_20240327-202050/train_y_m_loudener_2_classes_1.4_seconds_20240327-202050
