
model_parameters:
  kernel_conv_1: 2
  stride_conv_1: 1
  padding_conv_1: 0
  out_conv_1: 6

  kernel_conv_2: 3
  stride_conv_2: 1
  padding_conv_2: 0
  out_conv_2: 16

  kernel_conv_3: 5
  stride_conv_3: 1
  padding_conv_3: 0
  out_conv_3: 40

  kernel_pool: 2
  stride_pool: 2
  padding_pool: 0

  out_fc1: 400
  out_fc2: 200
  out_fc3: 84



  num_classes: 5



train_loop:
  # name and location of pickles
  x_train_address: '/pickles/nsynth_train_x'
  y_train_address: '/pickles/nsynth_train_y'
  x_test_address: '/pickles/nsynth_test_x'
  y_test_address: '/pickles/nsynth_test_y'




  classes:
    #c_1: 'guitar'
    #c_2: 'piano'
    #c_3: 'drum'
    #c_4: 'violin'

    c_1: 'bass_el'
    c_2: 'string_ac'
    c_3: 'guitar_el'
    c_4: 'keys_ac'
    c_5: 'keys_el'


  learning_rate: 0.0001
  num_epochs: 3

  # For the scheduler:
  step_size: 10
  gamma: 0.5

  model_results_address: '/model_results/'