model_name: name
model_parameters:
  dropout_probab: 0.35
  kernel_conv_1: 2
  kernel_conv_2: 3
  kernel_conv_3: 5
  kernel_pool_1: 2
  kernel_pool_2: 4
  kernel_pool_3: 5
  num_classes: 13
  out_conv_1: 6
  out_conv_2: 16
  out_conv_3: 40
  out_fc1: 400
  out_fc2: 200
  out_fc3: 84
  padding_conv_1: 2
  padding_conv_2: 2
  padding_conv_3: 2
  padding_pool_1: 1
  padding_pool_2: 2
  padding_pool_3: 2
  stride_conv_1: 1
  stride_conv_2: 1
  stride_conv_3: 1
  stride_pool_1: 2
  stride_pool_2: 3
  stride_pool_3: 3
preprocessing:
  address_for_mel_spectrograms: /Users/cookie/dev/m_loudener/audio_files/_train_test_dataset/mels_
  after_trim: pad
  duration_sec: 1
  fft_hop: 512
  fft_size: 2048
  filter_dc: true
  fmax: 8000
  librosa_trim_db: 15
  mel_power: 1.0
  mel_size: 512
  number_of_files_per_class_train: 100
  number_of_files_test: 1300
  number_of_files_train: 1300
  number_of_shifted_spectrograms: 1
  sample_rate: 16000
  stft_center: false
  time_size: 28
  to_save_pickles: null
  train_test_files_destination_folder: /Users/cookie/dev/m_loudener/audio_files/_train_test_dataset/
train_loop:
  classes:
    c_1: Drum_Kits
    c_10: Piano
    c_11: String
    c_12: Brass
    c_13: Flute
    c_2: Drums_Kick
    c_3: Drums_Tom
    c_4: Drums_Snare
    c_5: Drums_Hat
    c_6: Vocals
    c_7: Bass
    c_8: Guitar_Acoustic
    c_9: Guitar_Electric
  gamma: 0.5
  learning_rate: 2.0e-06
  model_results_address: /model_results/m_loudener/
  num_epochs: 2
  step_size: 15
  type_of_training: /Users/cookie/dev/instrument_classifier/model_results/m_loudener/multi_class_models/lr_7e-05_epochs_180_20240330-023211/lr_7e-05_epochs_180_20240330-023211.pt
  validation_set: /Users/cookie/dev/m_loudener/audio_files/_train_test_dataset/Validation_Set/
  x_test_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_13_classes_1_seconds_20240406-063755/test_x_m_loudener_13_classes_1_seconds_20240406-063755
  x_train_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_13_classes_1_seconds_20240406-063755/train_x_m_loudener_13_classes_1_seconds_20240406-063755
  y_test_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_13_classes_1_seconds_20240406-063755/test_y_m_loudener_13_classes_1_seconds_20240406-063755
  y_train_address: /Users/cookie/dev/m_loudener/pickles/m_loudener_13_classes_1_seconds_20240406-063755/train_y_m_loudener_13_classes_1_seconds_20240406-063755
