"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui.py']
DATA_FILES = ['/model_results/lr_0.0002_epochs_140_20231219-132849.pt']
OPTIONS = {'packages': ['pathlib', 'PySimpleGUI', 'matplotlib', 'matplotlib.pyplot', 'librosa.effects'], 'includes': ['os', 'numpy', 'librosa', 'librosa.display', 'librosa.effects', 'torch', 'torchvision', 'pickle', 'sys', 'matplotlib.pyplot']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
